[package]
name = "caissa-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "caissa"
path = "src/main.rs"

[dependencies]
caissa-core = { path = "../caissa-core" }
tokio = { workspace = true }
clap = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
reqwest = { workspace = true }
chrono = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
axum = { workspace = true }
uuid = { workspace = true }
kube = { workspace = true }
k8s-openapi = { workspace = true }
serde_yaml = { workspace = true }
aws-sdk-s3 = { workspace = true }
aws-config = { workspace = true }
aws-credential-types = { workspace = true }
rustls = { workspace = true }
hmac = { workspace = true }
sha1 = { workspace = true }
hex = { workspace = true }
fondament-core = { workspace = true }
pulldown-cmark = { workspace = true }

[dev-dependencies]
wiremock = "0.6"
