apiVersion: v1
kind: Namespace
metadata:
  name: occitan-system
  labels:
    {{- include "occitan.labels" . | nindent 4 }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: agents
  labels:
    {{- include "occitan.labels" . | nindent 4 }}
