image: ghcr.io/miegjorn/fondament-server
imageTag: sha-fbc341d
port: 7800
definitionsPath: /fondament/definitions
fargaUrl: http://farga.occitan-system.svc.cluster.local:7500
registryUrl: http://minio.occitan-system.svc.cluster.local:9000
registryBucket: fondament-registry
replicas: 1
